name: Docs

on:
  workflow_dispatch:
  workflow_call:
    inputs:
      plan:
        required: false
        type: string

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/checkout@v6
      - name: Install mdbook
        run: |
          tag=$(curl -s 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir mdbook
          curl -sSL $url | tar -xz --directory=./mdbook
          echo "$(pwd)/mdbook" >> $GITHUB_PATH
      - run: mdbook build docs
      - name: Generate sitemap
        uses: cicirello/generate-sitemap@v1
        with:
          base-url-path: https://ayarotsky.github.io/diesel-guard/
          path-to-root: docs/book
          exclude-paths: print.html 404.html
      - uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book
      - uses: actions/deploy-pages@v4
        id: deployment
